apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main-applicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/ghebu/argocd-sandbox.git 
      revision: main 
      directories:
      - path: "apps/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ghebu/argocd-sandbox.git 
        targetRevision: main
        path: 'apps'
      destination:
        # Default base cluster
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

