apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appprojects
  namespace: argocd-customer
spec:
  project: default 
  source:
    path: apps-demo 
    repoURL: https://github.com/ghebu/argocd-sandbox.git 
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: argocd-customer 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true

